name: publish

on:  
  push:
    tags:
      - '*'

jobs:
  publish-twitch-recorder-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT }}

    - name: Build the twitch-recorder Docker image
      run: |
        docker build . --tag ghcr.io/jawee/twitch-recorder:latest
        docker push ghcr.io/jawee/twitch-recorder:latest
